apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/managed-by: Helm
data:
  jenkins.yaml: |
    ${file("${path.module}/jasc/jenkins.yaml")}
